### ISSUE TITLE
会议结束后直接黑屏

### ISSUE THREAD

**Issue by commandf1** [CognifyDev/ClashOfGods#49]
没有任何报错
有警告产生
~~~
[Message:     Unity] Opening meeting room: commandf1 (PlayerControl)
[Warning:     Unity] Rewired: [WARNING] No Action exists for Action Id 0. You can create Actions in the editor.
~~~

这时候创建房间有报错产生
~~~
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.Object.get_name () [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at UnityEngine.Object.get_name()
   at COG.Utils.PlayerUtils.IsSamePlayer(PlayerControl player, PlayerControl target) in D:\RiderProjects\ClashOfGods\COG\Utils\PlayerUtils.cs:line 40
   at COG.Utils.PlayerUtils.<>c__DisplayClass5_0.<GetRoleInstance>b__0(KeyValuePair`2 keyValuePair) in D:\RiderProjects\ClashOfGods\COG\Utils\PlayerUtils.cs:line 46
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at COG.Utils.PlayerUtils.GetRoleInstance(PlayerControl player) in D:\RiderProjects\ClashOfGods\COG\Utils\PlayerUtils.cs:line 45
   at COG.Role.Role.<AddButton>b__44_0() in D:\RiderProjects\ClashOfGods\COG\Role\Role.cs:line 110
   at COG.UI.CustomButtons.CustomButton.Update() in D:\RiderProjects\ClashOfGods\COG\UI\CustomButton\CustomButton.cs:line 163
   at COG.Listener.Impl.CustomButtonListener.OnHudUpdate(HudManager manager) in D:\RiderProjects\ClashOfGods\COG\Listener\Impl\CustomButtonListener.cs:line 14
   at COG.Patch.HudManagerPatch.OnHudUpdate(HudManager __instance) in D:\RiderProjects\ClashOfGods\COG\Patch\CustomButtonsPatch.cs:line 19
   at DMD<HudManager::Update>(HudManager this)
   at (il2cpp -> managed) Update(IntPtr , Il2CppMethodInfo* )
~~~

**Comment by JieGeLovesDengDuaLang** [comment]
警告多半是树懒自己的问题，因为发警告的是Unity
第二个我猜猜，是GetRoleInstance方法返回了null，导致CustomButton出现空引用，加个null判断，如果是null返回未知职业就行

**Comment by commandf1** [comment]
报错原因可能是退出房间信息依然存在，这个不是大问题
但是会议结束后会直接黑屏，没有任何报错

**Comment by JieGeLovesDengDuaLang** [comment]
要不在会议结束监听器那里一行一行地try catch![doge](https://i0.hdslb.com/bfs/emote/3087d273a78ccaff4bb1e9972e2ba2a7583c9f11.png@48w_48h.webp)

**Comment by commandf1** [comment]
> 要不在会议结束监听器那里一行一行地try catch![doge](https://camo.githubusercontent.com/60215d0abe83675857cc2c4035439d6f5ba6685a8360b5606597310dfb872836/68747470733a2f2f69302e6864736c622e636f6d2f6266732f656d6f74652f333038376432373361373863636166663462623165393937326532626132613735383363396631312e706e67403438775f3438682e77656270)
这样写是吧 好好好

**Comment by ZsFabTest** [comment]
我觉得有可能是上一局的Sheriff数据未清除 在新房间中试图添加击杀键导致报错

**Comment by ZsFabTest** [comment]
应该往这个方面想

**Comment by ZsFabTest** [comment]
所有调用了报红的函数的职业只有警长和小丑

**Comment by ZsFabTest** [comment]
所有调用了报红的函数的职业只有警长和小丑

**Comment by ZsFabTest** [comment]
报错信息中有提到在AddButton处调用了报红的函数

**Comment by commandf1** [comment]
我尝试取消注册 小丑 & 警长 职业，看看会不会还有问题出现

**Comment by commandf1** [comment]
试了，然后没用，依然黑屏
我尝试取消Patch method

**Comment by commandf1** [comment]
取消所有Patch之后，会议不会黑屏

**Comment by ZsFabTest** [comment]
~~那就try catch吧~~      
估计不影响运行...

**Comment by commandf1** [comment]
依然没有任何报错，已经紫砂了

**Comment by JieGeLovesDengDuaLang** [comment]
试试只patch一个更改游戏最小人数再开始游戏，不知道这样会不会黑屏

**Comment by JieGeLovesDengDuaLang** [comment]
破案了，树懒的问题
